import { Inter } from 'next/font/google'
import './globals.css'
import NavbBar from '@/components/navbar/NavbBar'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
